### ISSUE TITLE
shield block and infused quantum chestplate recipe

### ISSUE THREAD

**Issue by quentfr21** [fewizz/Electro-Magic-Tools#10]
hello
forge 10.13.4.1492
EMT 1.2.2

i can't craft shield block in arcane workbench
i get shield block in creative and try to make infused quantum chestplate and nothing come when i use my wand on infusion table

thank in advance

**Comment by fewizz** [comment]
(now?)[https://drive.google.com/file/d/0B0GYhmakgvItbVhxRElRbURXWUE/view?usp=sharing]

**Comment by quentfr21** [comment]
hello

no more problem with this build 

thanks for the quick fix and for the rebirth of this great mod

**Comment by quentfr21** [comment]
another little thing about electric google 
when you try to craft it you need to charge re-battery before or recipe not work 
thanks

**Comment by Dream-Master** [comment]
I can confirm now see a recipes from shield block.
![screenshot 2015-10-11 16 25 10](https://cloud.githubusercontent.com/assets/2970688/10417245/bcde4282-7034-11e5-8f29-e918e9e74d9e.png)

**Comment by Dream-Master** [comment]
Many other Recipes not showing the recipes in Nei (Thaumic Nei Plugin) So i guess they have to reworked too.
@fewizz maybe you can check this in our pack.

**Comment by fewizz** [comment]
Can you suggest me a recipe for crystallized matter? =P

**Comment by Dream-Master** [comment]
Sure but i thinke my recipe are ultra hard :-)
I think about one and post it.

**Comment by quentfr21** [comment]
hello

i think three way to get crystalized

--a new machine
that accept ic2 liquid-uu and maybe powered to switch between liquid-uu to crystalized matter (maybe consume 120mb of liquid-uu for 8 or more crystalized uu) 120mb with ic2 replicator is 1 iridium
this way need more work for you

--a crucible recipe 
like use 1 uu-matter cell (one bucket) and some praecantatio to get some crystalized uu (maybe adjustable in config if possible)

--an arcane workbench recipe
like same as crucible

we need to don't forget liquid uu-matter if already hard to get so we need a way not too hard to match recipe of crystalized uu in infusion table ( don't want use 2 bucket of uu to get 64 of coal for example :))

thanks

**Comment by Dream-Master** [comment]
@quentfr21 "we need to don't forget liquid uu-matter is already hard to get so we need a way not too hard to match recipe of crystalized uu in infusion table ( don't want use 2 bucket of uu to get 64 of coal for example :))"

Than you never played with Gregtech or using my pack :-)

@fewizz A crucible recipes is a good Idea maybe using a uu matter cell and some perditio and some praecantatio to craft it.

With Gregtech you add recipes in the Brewing Machine the Refinery or the chemical bath for example.

Making a complete new machine for only one item not make sense.

Not sure how powerfull the crystalized UU Mater is but get 64 for one bucket is a bit to cheap i think.
(config option will help here to adjust the amount a bit)

**Comment by quentfr21** [comment]
@Dream-Master 
yep i don't use greg tech i make a personal pack with friends

but we have to think with only ic2 EMT and thaumcraft installed first
and add a config for user have mod like greg tech for example 

if you have only this three mod 64 crystalized is already not enough to match 120mb uu for 1 iridium

thanks

**Comment by fewizz** [comment]
[now?](https://drive.google.com/file/d/0B0GYhmakgvItQ3RVcWlrcG0yeWc/view?usp=sharing)

**Comment by quentfr21** [comment]
hello again

-recipe for portable node work
-recipe for electric goggle with "raw" re-battery work
-recipe for cristazed uu work but i think it's really hard we need more than 1 in crucible recipe or other recipe with cristalized become useless (in my point of view) 

thanks again for your time

**Comment by Dream-Master** [comment]
@fewizz 
For my taste the recipe is ok mean in my pack :+1:
