### ISSUE TITLE
One Ring

### ISSUE THREAD

**Issue by TerdyTheTerd** [fewizz/Electro-Magic-Tools#11]
Whenever I equip the one ring, my character flashes invisible for a spit second but then is visible again. Using latest custom build 1.2.0B2 and forge 1448

**Comment by fewizz** [comment]
Please, try 1.2.4.

**Comment by TerdyTheTerd** [comment]
Sorry for the delayed response on my part, ring is fixed now and working, even with kcauldron, thanks a bunch
