### ISSUE TITLE
Uncraftable Inventory/Armor Charging Ring?

### ISSUE THREAD

**Issue by 3TUSK** [fewizz/Electro-Magic-Tools#13]
![image](https://cloud.githubusercontent.com/assets/9113033/11458826/3759f880-9696-11e5-98c0-32d582026535.png)
While I am working around my new magic-theme pack, I notice that both inventory charging ring and armor charging ring use _wind mill_ and _water mill_, rather than _kinetic wind generator_ and _kinetic water generator_, in their infusion recipe. However, the recipe for _wind mill_ has been removed since [`build #634`](http://jenkins.ic2.player.to/job/IC2_experimental/634/changes#fb381baf6bdce3339951aeda3785680f853d4038). I didn't found when the water mill recipe was removed, but it is uncraftable as well. Thus, neither of these rings can be made.
I wonder whether it is a _feature_ or an actual bug? Just curious about that.

**Comment by 3TUSK** [comment]
And also I am using IC2exp Build 799 and EMT 1.2.3.
![image](https://cloud.githubusercontent.com/assets/9113033/11458904/dd52c5b8-9697-11e5-9aa3-27fc57ec81e3.png)

**Comment by fewizz** [comment]
I will just remove water mill from recipe. ok?

**Comment by 3TUSK** [comment]
How about using kinetic wind generator and kinetic water generator.

**Comment by fewizz** [comment]
hmm... ok.
