### ISSUE TITLE
New shield focus can't block projectiles properly

### ISSUE THREAD

**Issue by HaruDasom** [fewizz/Electro-Magic-Tools#17]
Forge Version : 1.7.10 - 1448
Thaumcraft : 4.2.3.5
Industrial Craft : experimental 772
Electro-Magic-Tools : 1.2.5

Projectiles(arrow, blaze fireball, ...) deal same damage whether using the shield focus or not

**Comment by fewizz** [comment]
hmm.. ok, i will look into this.
