### ISSUE TITLE
Nano Boots of the Traveller don't make the player go faster at all

### ISSUE THREAD

**Issue by gonglinyuan** [fewizz/Electro-Magic-Tools#20]
Version: EMT 1.2.5, IC2EXP build-810, TC4.2.3.5
Nano Boots of the Traveller can make the player jump higher, and the player wearing it can walk onto one-block-high block without jumping, but it don't speed the player at all.

**Comment by Schevv** [comment]
Try to enable the speed boost by pressing the (IC2) boost key and mode switch key at the same time

**Comment by fewizz** [comment]
works for me. =P
