### ISSUE TITLE
Сапоги путешествиника

### ISSUE THREAD

**Issue by Titan2008** [fewizz/Electro-Magic-Tools#22]
Электрические сапоги путешественника не дают увеличение скорости, также как и последующие улучшения. Почему?

**Comment by Schevv** [comment]
See #20 , need to press (IC2) boost key and mode switch key at the same time
(sorry cant reply in your language)

**Comment by Titan2008** [comment]
How to do it? I really don't know.

**Comment by Schevv** [comment]
Look into your Key-Configuration. You need a key bound to IC2 Boost and IC2 Mode switch. Then, while wearing the boots press both keys simultaneously.
With that it works for me
