### ISSUE TITLE
Diamond Chainsaw can't shear

### ISSUE THREAD

**Issue by MauveCloud** [fewizz/Electro-Magic-Tools#23]
Upgrading a chainsaw with diamonds causes it to place torches with a right-click (not mentioned at all in either chainsaw Thaumonomicon entry), and it loses the ability to shear sheep, leaves, and grass, which according to the Thaumonomicon entries is only supposed to happen upon upgrading it to Thaumium level.  The regular IC2 chainsaw allowed me to toggle shearing with "mode switch key" + "use item", but that has no effect with the diamond chainsaw.

**Comment by fewizz** [comment]
Ouch :smile: , ok. I will look...

**Comment by fewizz** [comment]
If you want to test: (1.2.6_beta_1)[https://drive.google.com/file/d/0BwY_2FEZWt8dZHg4VHphSFFwRFE/view?usp=sharing]

**Comment by MauveCloud** [comment]
I don't mind the torches, even if it's still undocumented.
Toggling the shearing works now, and shearing leaves and grass works now (when toggled on), but shearing sheep (with a right click) still doesn't work in the 1.2.6_beta_1 you provided.

**Comment by fewizz** [comment]
hmm, ok. i will look again.

**Comment by fewizz** [comment]
[1.2.6_beta_2](https://drive.google.com/file/d/0BwY_2FEZWt8dUk16NEtBYTd3akU/view?usp=sharing)

**Comment by MauveCloud** [comment]
Confirmed.  Shearing sheep works in that build.
