### ISSUE TITLE
[Question] New Version

### ISSUE THREAD

**Issue by Dream-Master** [fewizz/Electro-Magic-Tools#24]
@fewizz 

I like this mod and want to ask when we get a new Version. 1.2.5 is from December.

**Comment by fewizz** [comment]
Sorry @Dream-Master , [i haven't time atm](https://ru.wikipedia.org/wiki/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%8D%D0%BA%D0%B7%D0%B0%D0%BC%D0%B5%D0%BD).

**Comment by Dream-Master** [comment]
Np. Take your time.

**Comment by Dream-Master** [comment]
@fewizz
Any new here. Get we a new version with the stuff you updatet allready?
Maybe a last one for 1.7.10.

**Comment by Dream-Master** [comment]
:+1:

**Comment by fewizz** [comment]
I hope that new version not buggy ;3

**Comment by Dream-Master** [comment]
I let you know if after the next Server Update.
