### ISSUE TITLE
Bug with Greg Tech

### ISSUE THREAD

**Issue by THEVOLCO** [fewizz/Electro-Magic-Tools#25]
Hi,
When I launch the game I get following crash report:
http://pastebin.com/GkB8ggW4
Can you help me pls?

**Comment by fewizz** [comment]
Update to [latest](http://minecraft.curseforge.com/projects/electro-magic-tools) version

**Comment by THEVOLCO** [comment]
Nope, with version 1.2.5. I still get the same crash report :(
