### ISSUE TITLE
Cannot make Wand Focus: Charging

### ISSUE THREAD

**Issue by Kyrnterra** [fewizz/Electro-Magic-Tools#26]
EMT version 1.2.5

Following the recipe in NEI or the Thaumicon and clicking the Infusion Matrix with a wand and the infusion will not start. I tried different combinations of shards with no success.

**Comment by fewizz** [comment]
Will look =_=

**Comment by fewizz** [comment]
Works for me O_o 
![2016-07-30_19 41 33](https://cloud.githubusercontent.com/assets/8060034/17271771/b8151c36-568d-11e6-9c09-5cb93ac5476b.png)
