### ISSUE TITLE
Gregtech Recipe Compatibility Issue

### ISSUE THREAD

**Issue by ArticulatedDrunk** [fewizz/Electro-Magic-Tools#27]
So I'm running into a crash with your mod and gregtech. I posted some details on your curse page but I'll repost the error log here.  http://pastebin.com/9wa3VveQ

**Comment by ArticulatedDrunk** [comment]
Seems to be a problem with a specific recipe.

**Comment by fewizz** [comment]
Already fixed, but not released.

**Comment by ArticulatedDrunk** [comment]
Cool so when are we getting this release?

**Comment by fewizz** [comment]
soon.

**Comment by fewizz** [comment]
You can find new version on curse.
