### ISSUE TITLE
No fall damage reduction in any of the wing classes.

### ISSUE THREAD

**Issue by Dream-Master** [fewizz/Electro-Magic-Tools#29]
@fewizz The Fall Damage Ignored when you have wings on you. It make no difference if you have Duct Tape wings or Quantum on you.

https://github.com/fewizz/Electro-Magic-Tools/tree/master/src/main/java/emt/item/armor/wings

After looking into the code and talk with some other Devs I can't find any indication of damage reduction in any of the wing classes.

**Comment by Dream-Master** [comment]
https://github.com/fewizz/Electro-Magic-Tools/tree/master/src/main/java/emt/item/armor/wings

**Comment by Technus** [comment]
Isn't that supposed to be done by nano/quantum boots?

IIRC even IC2 does it like that.

**Comment by Dream-Master** [comment]
@fewizz 
Mh ok Feather wings not have any fall damage and Quantum 100%. But I am against Nano have 100 too.
Can you add 50% to Nano and 25% to Feather would be nice.

**Comment by fewizz** [comment]
Hmm, ok, good idea
