### ISSUE TITLE
Cant elevate up on OpenBlocks Elevator while wearing Nano Boots Of The Traveller

### ISSUE THREAD

**Issue by TrainerSnow** [fewizz/Electro-Magic-Tools#45]
While wearing the Nano Boots of the Travelle, im unable to use the "openblock"'s elevator block upwards. I can elevate downwards, but jumping upwards wont teleport me to the elevator directly above it. When i take the boots off while standing on the elevator, without changing my location, the "openblock"'s elevator works flawlessly. 
Modpack : GT:NH

**Comment by Dream-Master** [comment]
@TrainerSnow 
please report it here
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues
thanks
