### ISSUE TITLE
Relicense under the MIT

### ISSUE THREAD

**Issue by Adaptivity** [fewizz/Electro-Magic-Tools#9]
Electro-Magic Tools was originally licensed under GNU GENERAL PUBLIC LICENSE. fewizz and I want to change current license to MIT. However, we need confirmation from all contributors.
@Tombenpotter, @TehNut can you confirm this guys? All we need from you is "No" or "Yes". We will glad if you confirm this rather than deny.

**Comment by TehNut** [comment]
*Why?*

**Comment by Adaptivity** [comment]
Just because it's suits more. A lot of mods using MIT and current fewizz's mods are using it too. So, why not?

**Comment by TehNut** [comment]
That's not a very good reason...

**Comment by Adaptivity** [comment]
Ok, we can leave GNU then.
